### ISSUE TITLE
Add getEntityClassNames method to repositories

### ISSUE THREAD

**Issue by f3l1x** [contributte/nextras-orm-generator#1]
Idea: https://github.com/Zarganwar/normgen/commit/662c50bd1dccbf81388fd5cbca42d420c4406d48

**Comment by SiViN** [comment]
My idea.. https://github.com/SiViN/normgen/commit/6a8d30f8e862754f2a1cfe7e694b638eea1d7f42 inspired by Zarganwar

**Comment by f3l1x** [comment]
Thank you. 

Resolved via #2
