### ISSUE TITLE
Docs & examples

### ISSUE THREAD

**Issue by f3l1x** [contributte/nextras-orm-generator#11]
- Example is more then 1000 words, right?
  - Let's create some example to our playground repo - https://github.com/contributte/playground.
- Improve docs with basic usage.

**Comment by f3l1x** [comment]
Any progress @dakorpar ?

**Comment by dakorpar** [comment]
@f3l1x We have  new version ready just testing some stuff and in order to see if all ok I have to do some progress on private repo project to test everything and make sure it's correct. After that I'll add up examples and then we can release new version. Shuld be done through this week.

**Comment by f3l1x** [comment]
👍 Awesome.

**Comment by f3l1x** [comment]
I am thinking about some blogpost about "How to convert from active record to Nextras ORM". WDYT?
