### ISSUE TITLE
Related projects

### ISSUE THREAD

**Issue by f3l1x** [contributte/nextras-orm-generator#17]
- https://github.com/nattreid/orm
- https://github.com/Zarganwar/nextras-orm-generator
- https://github.com/Barbarossa-42/nextras-orm-command
- https://github.com/martenb/nextras-orm-code-generator

----

I would love to see some cooperation on one package. What do you think guys? 

@martenb @Barbarossa-42 @Zarganwar @nattreid 

Cc @dakorpar

**Comment by mabar** [comment]
nattreid/orm
  - creates tables in runtime through a sql builder - generate base sql from entities and execute it through nextras/migrations would be preferable

Zarganwar/nextras-orm-generator
Barbarossa-42/nextras-orm-command
 - everything already implemented by this package

martenb/nextras-orm-code-generator
 - allows configure base directory, namespace and which classes are extended - basically nice idea. I am just thinking last few weeks about a generic code generator which would create code from a configurable schema

**Comment by martenb** [comment]
If you wan't to integrate my package, I can cooperate to help you with it...

**Comment by martenb** [comment]
I was thinking to rewrite my generator to composer script (no dependency on symfony/console, nette/di), is this the right way of merging these packages?

**Comment by Zarganwar** [comment]
I am able to cooperate but idk if integration of my old generator is to something. It's old and for old version of orm. I don't use this orm currently 🤕

**Comment by f3l1x** [comment]
@martenb I think it might be, but is it really needed? I mean I've only used this type of generator to start new project. Symfony Console could be opt-in.

@Zarganwar I see, thus it's okey and we keep it just like that. Thanks for comment.

**Comment by martenb** [comment]
In my case i used it everytime i need to create new entity, so no just at the start of project. Composer script could be easier to use for beginners i think.

**Comment by martenb** [comment]
@mabar 

Currently, I am working on generic code generator. What do you think about that?

https://packagist.org/packages/adbros/worker

**Comment by f3l1x** [comment]
Looks great, how far are you?

**Comment by f3l1x** [comment]
Closing it now.
