### ISSUE TITLE
compatibility with nette 3.0

### ISSUE THREAD

**Issue by pytelCZ** [contributte/nextras-orm-generator#21]
for version 0.2
`Problem 1
  - Installation request for contributte/nextras-orm-generator ^0.2.0 -> satisfiable by contributte/nextras-orm-generator[0.2].
  - contributte/nextras-orm-generator 0.2 requires nette/database ^2.4.0 -> satisfiable by nette/database[v2.4.0, v2.4.1, v2.4.10, v2.4.2, v2.4.3, v2.4.4, v2.4.5, v2.4.6, v2.4.7, v2.4.8, v2.4.9, v2.4.x-dev] but these conflict with your requirements or minimum-stability.`

for version dev 0.3
`Problem 1
  - nette/php-generator v2.5.0 requires nette/utils ~2.4 -> satisfiable by nette/utils[v2.4.0, v2.4.1, v2.4.10, v2.4.2, v2.4.3, v2.4.4, v2.4.5, v2.4.6, v2.4.7, v2.4.8, v2.4.9, v2.4.x-dev, v2.5.0, v2.5.1, v2.5.2, v2.5.3, v2.5.4, v2.5.x-dev] but these conflict with your requirements or minimum-stability.
  - Installation request for contributte/nextras-orm-generator 0.3.x-dev -> satisfiable by contributte/nextras-orm-generator[0.3.x-dev].
  - Conclusion: remove nette/utils v3.1.2
  - Conclusion: don't install nette/utils v3.1.2
  - contributte/nextras-orm-generator 0.3.x-dev requires nette/php-generator ^2.5|3.1 -> satisfiable by nette/php-generator[v2.5.0, v2.6.0, v2.6.1, v2.6.2, v2.6.3, v2.6.4, v3.1.0].
  - nette/php-generator v2.6.0 requires nette/utils ^2.4.2 || ~3.0.0 -> satisfiable by nette/utils[v3.0.0, v3.0.1, v3.0.2, v3.0.3].
  - nette/php-generator v2.6.1 requires nette/utils ^2.4.2 || ~3.0.0 -> satisfiable by nette/utils[v3.0.0, v3.0.1, v3.0.2, v3.0.3].
  - nette/php-generator v2.6.2 requires nette/utils ^2.4.2 || ~3.0.0 -> satisfiable by nette/utils[v3.0.0, v3.0.1, v3.0.2, v3.0.3].
  - nette/php-generator v2.6.3 requires nette/utils ^2.4.2 || ~3.0.0 -> satisfiable by nette/utils[v3.0.0, v3.0.1, v3.0.2, v3.0.3].
  - nette/php-generator v2.6.4 requires nette/utils ^2.4.2 || ~3.0.0 -> satisfiable by nette/utils[v3.0.0, v3.0.1, v3.0.2, v3.0.3].
  - nette/php-generator v3.1.0 requires nette/utils ^2.4.2 || ~3.0.0 -> satisfiable by nette/utils[v3.0.0, v3.0.1, v3.0.2, v3.0.3].
  - Can only install one of: nette/utils[v3.0.0, v3.1.2].
  - Can only install one of: nette/utils[v3.0.1, v3.1.2].
  - Can only install one of: nette/utils[v3.0.2, v3.1.2].
  - Can only install one of: nette/utils[v3.0.3, v3.1.2].
  - Installation request for nette/utils (locked at v3.1.2, required as ^3.0) -> satisfiable by nette/utils[v3.1.2].`

**Comment by f3l1x** [comment]
Fixed and bumped v0.3.
