### ISSUE TITLE
Generating relationship parameter in entity

### ISSUE THREAD

**Issue by krausv** [contributte/nextras-orm-generator#35]
Hi, thank for this amazing tool!

If I can have a question...

Is it possible to generate an entity without overwriting relationship?

Example:

I have some entity

```
/**
 * @property int $id {primary}
 * @property string|NULL $slug
 * @property CarClass|NULL $class {m:1 CarClass, oneSided=true}
 */
class Orders extends AbstractEntity
{
}
```

And if I add some new cols in db and re-run generator:

```
/**
 * @property int $id {primary}
 * @property string|NULL $slug
 * @property CarClass $class {??? CarClass::$???}
 * @property string|NULL $status
 */
class Orders extends AbstractEntity
{
}
```

Is possible somehow fix that? 

Thanks for your reply!

**Comment by f3l1x** [comment]
Hi. Unfortunately it's not possible. This si simple library, that overrides all files. It would require some kind of parsing and it's too complex. If you use git, you can version your files and revert lines. :-)

**Comment by krausv** [comment]
Hi, thanks for your reply. It doesn't matter :-)
