### ISSUE TITLE
Argument #1 ($default) must be of type string, null given

### ISSUE THREAD

**Issue by MKI-Miro** [contributte/nextras-orm-generator#36]
Hi when I try to run this code I got error below.

PHP 8.2
MariaDB 10.05

`<?php

declare(strict_types=1);

use Contributte\Nextras\Orm\Generator\Analyser\Database\DatabaseAnalyser;
use Contributte\Nextras\Orm\Generator\Config\Impl\TogetherConfig;
use Contributte\Nextras\Orm\Generator\SimpleFactory;

require_once __DIR__ . '../../vendor/autoload.php';

$config = [
    'output' => __DIR__ . '/model-nextras',
    //other options
    ];
$factory = new SimpleFactory(
    new TogetherConfig($config),
    new DatabaseAnalyser('....', '.....', '.....')
);

$factory->create()->generate();`

`Fatal error: Uncaught TypeError: Contributte\Nextras\Orm\Generator\Entity\Column::setDefault(): Argument #1 ($default) must be of type string, null given, called in \vendor\contributte\nextras-orm-generator\src\Analyser\Database\DatabaseAnalyser.php on line 69 and defined in \vendor\contributte\nextras-orm-generator\src\Entity\Column.php:113 Stack trace: #0 \vendor\contributte\nextras-orm-generator\src\Analyser\Database\DatabaseAnalyser.php(69): Contributte\Nextras\Orm\Generator\Entity\Column->setDefault(NULL) #1 \vendor\contributte\nextras-orm-generator\src\Analyser\Database\DatabaseAnalyser.php(48): Contributte\Nextras\Orm\Generator\Analyser\Database\DatabaseAnalyser->analyseColumns(Object(Contributte\Nextras\Orm\Generator\Entity\Table)) #2 \vendor\contributte\nextras-orm-generator\src\Generator.php(87): Contributte\Nextras\Orm\Generator\Analyser\Database\DatabaseAnalyser->analyse() #3 \www\nextras.php(20): Contributte\Nextras\Orm\Generator\Generator->generate() #4 {main} thrown in \vendor\contributte\nextras-orm-generator\src\Entity\Column.php on line 113`

What can be wrong? Howcan I fix it?

Thanks

**Comment by lukasbruha** [comment]
Getting the same error as well after upgrading to 0.6.0. Tried dev-master, error persists. 0.5.0 works correctly.

**Comment by f3l1x** [comment]
Should be fixed https://github.com/contributte/nextras-orm-generator/releases/tag/v0.6.1
